### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by hugobloem** [dominik-strutz/dominik-strutz.github.io#1]
Hi Domi,

First of all, nice website. I just spotted two typos which you might want to fix 😊.

In [`Home`](https://github.com/dominik-strutz/dominik-strutz.github.io/blob/master/index.html): Locking --> Looking.

In [`About`](https://github.com/dominik-strutz/dominik-strutz.github.io/blob/master/about/index.html), line 121: you use 'use' twice. 

Cheers

**Comment by dominik-strutz** [comment]
Thanks, fixed in commit 32939c5.
